### ISSUE TITLE
Xcode 14.1 indicates that several files are missing

### ISSUE THREAD

**Issue by austintatiousness** [newtonresearch/newton-framework#1]
doc
DrawTextRejections.cc
NTKSupport.mm

**Comment by newtonresearch** [comment]
As you'll be able to tell, I'm not maintaining this project any more. But I don't think these files should be required to build the project.
doc is a folder of notes to myself;
DrawTextRejections.cc as the name implies contains text drawing code that I tried but rejected;
NTKSupport.mm contains implementations of FSetPartFrameSlot() and FGetPartFrameSlot() but I can't find these referenced anywhere else.
It's possible the repo is out of sync with my local copy, but it's also possible that my local copy didn't restore perfectly after the hard disk crash I had a couple of years ago.
