### ISSUE TITLE
Documentation request: Running byte code with newton-framework

### ISSUE THREAD

**Issue by MatthiasWM** [newtonresearch/newton-framework#2]
So I was able to compile the framework on my M1 Mac as an Intel 64 binary. Now I would love to run some byte code with it. Could you please post short example how to initialize the framework and how to run a NewtonScript bytecode method? Than you.

Unfortunately I can't get the MessagePad to compile. The linker fails with an internal error.

**Comment by MatthiasWM** [comment]
Trying to link Newton.framework in x86_64 mode, I get `ld: imageOffset32 fixup target must be defined` at the final link stage. I can't find any information on this error message. Do you have an idea?

**Comment by newtonresearch** [comment]
It has been a while since I touched any Newton stuff, so you probably know better than me! If you take a look at the newton-toolkit project, AppDelegate.mm, - (void)applicationDidFinishLaunching:(NSNotification *)inNotification you will see how that runs the GlobalInit.newtonscript file. Looking at Ref ParseFile(const char * inFilename) in newton-framework will give you more detail if you just need to execute a codeBlock.

The MessagePad target was work-in-progress. I can’t say I’m surprised the link fails, I may have checked it in that way. Sorry.

Hope this helps?

**Comment by MatthiasWM** [comment]
I hop I am not bothering you with my questions. Please let me know if I do ;-) .

Thanks, this does help. I am finding more little secrets, and I see now InitObjectSystem() gets everything up and running. I managed to compile and mostly link things now, but I get a crash, and I can't debug it on an M1. I'll have to borrow an Intel machine for debugging.

My first order is the attempt to get everything to compile without assembly code. It would make the library portable and future proof. It works ok for the ROMData, and I can skip the OS for now because I only want the framework for now. I struggle with P-Classes though.

Do you remember if Protocols are fundamentally different to C++ classes with inheritance and virtual methods? I understand that Protocols can add new derived classes at runtime which is great for vendor code. But for a library that is pretty much static in scope, I wonder if it is possible to replace the Intel code with modern C++?

**Comment by MatthiasWM** [comment]
Ok, I am a LOT further. I can compile for ARM, and rewriting the protocol factory, I can now single-step my way through the code. Sorry for repeating myself, but you have done amazing work here!

**Comment by MatthiasWM** [comment]
Ok, I did get the framework to run, compile, disassemble, decompile on ARM64, but the same code should Ron on Intel as well. https://github.com/MatthiasWM/newton-framework/tree/restructure . `cmake -B build && cmake --build build && build/test`.
